// ============================================================================
// lessel — GitHub-Based Plugin Registry
// Fetches plugins from the lessel-plugins GitHub repository.
// No server needed — uses raw.githubusercontent.com for data.
// ============================================================================

import crypto from 'crypto';
import path from 'path';
import fs from 'fs';

export interface GitHubPluginInfo {
  name: string;
  description: string;
  author: string;
  repository: string;
  schema: string[];
  engines: { lessel: string };
  tags: string[];
  latestVersion: string;
  versions: Record<string, {
    checksum: string;
    published: string;
    size: number;
  }>;
  totalVersions: number;
}

export interface RegistryIndex {
  generated: string;
  totalPlugins: number;
  plugins: GitHubPluginInfo[];
}

/**
 * Client for the lessel GitHub-based plugin registry.
 * Fetches plugin index and code from raw.githubusercontent.com.
 */
export class GitHubPluginRegistry {
  private repoOwner: string;
  private repoName: string;
  private baseUrl: string;

  constructor(repoOwner?: string, repoName?: string) {
    this.repoOwner = repoOwner || 'Terminay';
    this.repoName = repoName || 'lessel-plugins';
    this.baseUrl = `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/main`;
  }

  /**
   * Fetch the full registry index.
   */
  async fetchIndex(): Promise<RegistryIndex> {
    const url = `${this.baseUrl}/registry.json`;
    const res = await fetch(url);

    if (!res.ok) {
      throw new Error(`Failed to fetch plugin index: ${res.status} ${res.statusText}`);
    }

    return res.json() as Promise<RegistryIndex>;
  }

  /**
   * Search plugins by query string.
   */
  async search(query: string): Promise<GitHubPluginInfo[]> {
    const index = await this.fetchIndex();
    const q = query.toLowerCase();

    if (!q) return index.plugins;

    return index.plugins.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.author.toLowerCase().includes(q) ||
      (p.tags || []).some(t => t.toLowerCase().includes(q))
    );
  }

  /**
   * Get a specific plugin by name.
   */
  async getPlugin(name: string): Promise<GitHubPluginInfo> {
    const index = await this.fetchIndex();
    const plugin = index.plugins.find(p => p.name === name);
    if (!plugin) {
      throw new Error(`Plugin "${name}" not found in registry`);
    }
    return plugin;
  }

  /**
   * Download a plugin's index.js code.
   */
  async downloadPlugin(name: string, version?: string): Promise<{ code: string; version: string }> {
    const plugin = await this.getPlugin(name);
    const ver = version || plugin.latestVersion;

    if (!ver) {
      throw new Error(`No version specified and no latest version for "${name}"`);
    }

    const url = `${this.baseUrl}/plugins/${name}/${ver}/index.js`;
    const res = await fetch(url);

    if (!res.ok) {
      throw new Error(`Failed to download plugin "${name}@${ver}": ${res.status} ${res.statusText}`);
    }

    const code = await res.text();
    return { code, version: ver };
  }

  /**
   * Install a plugin from the registry into the local plugins directory.
   */
  async installPlugin(name: string, version?: string, targetDir?: string): Promise<string> {
    const plugin = await this.getPlugin(name);
    const { code, version: ver } = await this.downloadPlugin(name, version);

    // Create plugins directory
    const pluginsDir = targetDir || path.join(process.cwd(), 'plugins');
    const pluginDir = path.join(pluginsDir, name);
    const versionDir = path.join(pluginDir, ver);
    fs.mkdirSync(versionDir, { recursive: true });

    // Write the plugin code
    fs.writeFileSync(path.join(versionDir, 'index.js'), code);

    // Create a loader index.js at the plugin root
    const loaderCode = `// lessel plugin — "${name}" v${ver}
// Auto-generated by lessel registry
const plugin = require('./${ver}/index.js');
plugin.__registryPlugin = true;
module.exports = plugin;
`;
    fs.writeFileSync(path.join(pluginDir, 'index.js'), loaderCode);

    // Create package.json for discovery
    const pkg = {
      name: `@lessel/plugin-${name}`,
      version: ver,
      description: plugin.description,
      main: 'index.js',
      lessel: {
        registry: true,
        registryName: name,
        registryVersion: ver,
      },
    };
    fs.writeFileSync(path.join(pluginDir, 'package.json'), JSON.stringify(pkg, null, 2));

    console.log(`[lessel] ✅ Plugin "${name}" v${ver} installed to ${pluginDir}`);
    return pluginDir;
  }

  /**
   * Generate a plugin submission (opens a browser to create a PR).
   */
  async openPullRequest(name: string, pluginDir: string): Promise<void> {
    const prUrl = `https://github.com/${this.repoOwner}/${this.repoName}/compare/main...YOUR_BRANCH?quick_pull=1&labels=plugin`;
    console.log(`[lessel] To publish "${name}":`);
    console.log(`  1. Fork the plugin repo: https://github.com/${this.repoOwner}/${this.repoName}/fork`);
    console.log(`  2. Add your plugin to plugins/${name}/`);
    console.log(`  3. Create a Pull Request: ${prUrl}`);
    console.log(`  4. The registry will auto-build on merge`);
  }
}

/**
 * Generate SHA-256 checksum for plugin code.
 */
export function generatePluginChecksum(code: string | Buffer): string {
  return `sha256:${crypto.createHash('sha256').update(code).digest('hex')}`;
}